# This file lists the dependencies needed to build and test all of pyexactreal.
# # Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: pyexactreal-build
channels:
  - conda-forge
  - defaults
dependencies:
  - automake
  - boost-cpp==1.74.0
  - coreutils
  - cppyy>=2.1.0,<3
  - cppyythonizations>=1.1.3,<2
  - gmpxxyy>=1.0.1,<2
  - ipywidgets
  - libtool
  - make
  - pyeantic>=1.0.2,<2
  - pytest
  - sagelib
  - setuptools
  - sympy
  # valgrind is only needed for make check-valgrind
  # - valgrind
