{% set version = '2.3.0' %}
{% set build_number = '0' %}

package:
  name: pyexactreal
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # e-antic is not available on Windows yet
  skip: True  # [win]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - libexactreal
  run:
    - python
    - boost-cpp
    - cppyy
    - gmpxxyy>=1.0.1,<2
    - pyeantic

test:
  imports:
    - pyexactreal

about:
  home: https://github.com/flatsurf/exactreal
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Finite Real Submodules
