# Pins from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml
# so our packages is compatible with the choices made by conda-forge.
libflint:
  - '3'
libeantic:
  - '2'
boost_cpp:
  - '1.78.0'
gmp:
  - '6'
