{% set version = '2.3.0' %}
{% set build_number = '0' %}

package:
  name: libexactreal
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # e-antic is not available on Windows yet
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage("libexactreal", max_pin="x") }}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - arb {{ arb }}
    - boost-cpp {{ boost_cpp }}
    - libeantic >=1.0.0,<2
    - gmp {{ gmp }}

test:
  commands:
    - test -f ${PREFIX}/lib/libexactreal.so

about:
  home: https://github.com/flatsurf/exactreal
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Finite Real Submodules
