# This file lists the dependencies needed to build and test all of libexactreal
# using FLINT 2.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment-flint2.yml
name: libexactreal-build
channels:
  - conda-forge
dependencies:
  - automake
  - benchmark
  - boost-cpp==1.82.0
  - coreutils
  - cxx-compiler
  - libeantic>=1.3.0,<2
  - arb>=2.23,<2.24
  - libflint>=2,<3
  - gmp>6,<7
  - libtool
  - make
  # valgrind is only needed for make check-valgrind
  # - valgrind
